--------------------------------------------------------
--  파일이 생성됨 - 월요일-8월-14-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table NOTICE_TBL
--------------------------------------------------------

  CREATE TABLE "GAONNURIWEB"."NOTICE_TBL" 
   (	"NOTICE_NO" NUMBER, 
	"NOTICE_SUBJECT" VARCHAR2(500 BYTE), 
	"NOTICE_CONTENT" VARCHAR2(1000 BYTE), 
	"NOTICE_DATE" DATE DEFAULT SYSDATE, 
	"UPDATE_DATE" DATE DEFAULT SYSDATE, 
	"VIEW_COUNT" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RENTAL_TBL
--------------------------------------------------------

  CREATE TABLE "GAONNURIWEB"."RENTAL_TBL" 
   (	"RENTAL_USER" VARCHAR2(20 BYTE), 
	"RENTAL_PLACE" VARCHAR2(50 BYTE), 
	"RENTAL_DATE" DATE, 
	"RENTAL_HANBOK" VARCHAR2(50 BYTE), 
	"RENTAL_TOP_COLOR" VARCHAR2(50 BYTE), 
	"RENTAL_TOP_SIZE" VARCHAR2(50 BYTE), 
	"RENTAL_PANTS_COLOR" VARCHAR2(50 BYTE), 
	"RENTAL_PANTS_SIZE" VARCHAR2(50 BYTE), 
	"RENTAL_ACCESSORIES" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RESERVE_TBL
--------------------------------------------------------

  CREATE TABLE "GAONNURIWEB"."RESERVE_TBL" 
   (	"RESERVE_USER" VARCHAR2(20 BYTE), 
	"RESERVE_PLACE" VARCHAR2(10 BYTE), 
	"RESERVE_DATE" DATE, 
	"RESERVE_TIME" VARCHAR2(7 BYTE), 
	"RESERVE_PEOPLE" NUMBER, 
	"RESERVE_NAME" VARCHAR2(30 BYTE), 
	"RESERVE_PHONE" VARCHAR2(11 BYTE), 
	"RESERVE_EMAIL" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table USER_TBL
--------------------------------------------------------

  CREATE TABLE "GAONNURIWEB"."USER_TBL" 
   (	"USER_ID" VARCHAR2(20 BYTE), 
	"USER_PW" VARCHAR2(12 BYTE), 
	"USER_NAME" VARCHAR2(30 BYTE), 
	"USER_PHONE" VARCHAR2(11 BYTE), 
	"USER_EMAIL" VARCHAR2(50 BYTE), 
	"USER_EVENT_YN" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into GAONNURIWEB.NOTICE_TBL
SET DEFINE OFF;
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (1,'1번째 공지사항','1번째 공지사항 내용입니다.',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (2,'2번째 공지사항','2번째 공지사항 내용입니다.',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (3,'3번째 공지사항','3번째 공지사항 내용입니다.',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (4,'4번째 공지사항','4번째 공지사항 내용입니다.',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (5,'5번째 공지사항','5번째 공지사항 내용입니다.',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (6,'6번째 공지사항','6번째 공지사항 내용입니다.',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (7,'7번째 공지사항','7번째 공지사항 내용입니다.',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (8,'8번째 공지사항','8번째 공지사항 내용입니다.',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (9,'9번째 공지사항','9번째 공지사항 내용입니다.',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (10,'10번째 공지사항','10번째 공지사항 내용입니다.',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (11,'11번째 공지사항','11번째 공지사항 내용입니다.',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (12,'12번째 공지사항','12번째 공지사항 내용입니다.',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (13,'13번째 공지사항','13번째 공지사항 내용입니다.',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (14,'14번째 공지사항','14번째 공지사항 내용입니다.',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (15,'15번째 공지사항','15번째 공지사항 내용입니다.',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (16,'16번째 공지사항','16번째 공지사항 내용입니다.',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (17,'17번째 공지사항','17번째 공지사항 내용입니다.',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (18,'18번째 공지사항','18번째 공지사항 내용입니다.',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (19,'19번째 공지사항','19번째 공지사항 내용입니다.',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (20,'20번째 공지사항','20번째 공지사항 내용입니다.',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (21,'21번째 공지사항','21번째 공지사항 내용입니다.',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (22,'22번째 공지사항','22번째 공지사항 내용입니다.',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (23,'23번째 공지사항','23번째 공지사항 내용입니다.',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (24,'24번째 공지사항','24번째 공지사항 내용입니다.',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (25,'25번째 공지사항','25번째 공지사항 내용입니다.',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (26,'26번째 공지사항','26번째 공지사항 내용입니다.',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (27,'27번째 공지사항','27번째 공지사항 내용입니다.',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (28,'28번째 공지사항','28번째 공지사항 내용입니다.',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (29,'29번째 공지사항','29번째 공지사항 내용입니다.',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (30,'30번째 공지사항','30번째 공지사항 내용입니다.',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (31,'31번째 공지사항','31번째 공지사항 내용입니다.',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (32,'32번째 공지사항','32번째 공지사항 내용입니다.',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (33,'33번째 공지사항','33번째 공지사항 내용입니다.',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (34,'34번째 공지사항','34번째 공지사항 내용입니다.',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (35,'35번째 공지사항','35번째 공지사항 내용입니다.',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (36,'36번째 공지사항','36번째 공지사항 내용입니다.',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (37,'37번째 공지사항','37번째 공지사항 내용입니다.',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (38,'38번째 공지사항','38번째 공지사항 내용입니다.',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (39,'39번째 공지사항','39번째 공지사항 내용입니다.',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (40,'40번째 공지사항','40번째 공지사항 내용입니다.',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (41,'41번째 공지사항','41번째 공지사항 내용입니다.',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (42,'42번째 공지사항','42번째 공지사항 내용입니다.',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (43,'43번째 공지사항','43번째 공지사항 내용입니다.',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (44,'44번째 공지사항','44번째 공지사항 내용입니다.',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (45,'45번째 공지사항','45번째 공지사항 내용입니다.',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (46,'46번째 공지사항','46번째 공지사항 내용입니다.',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (47,'47번째 공지사항','47번째 공지사항 내용입니다.',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (48,'48번째 공지사항','48번째 공지사항 내용입니다.',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (49,'49번째 공지사항','49번째 공지사항 내용입니다.',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (50,'50번째 공지사항','50번째 공지사항 내용입니다.',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (51,'51번째 공지사항','51번째 공지사항 내용입니다.',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (52,'52번째 공지사항','52번째 공지사항 내용입니다.',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (53,'53번째 공지사항','53번째 공지사항 내용입니다.',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (54,'54번째 공지사항','54번째 공지사항 내용입니다.',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (55,'55번째 공지사항','55번째 공지사항 내용입니다.',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (56,'56번째 공지사항','56번째 공지사항 내용입니다.',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (57,'57번째 공지사항','57번째 공지사항 내용입니다.',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (58,'58번째 공지사항','58번째 공지사항 내용입니다.',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (59,'59번째 공지사항','59번째 공지사항 내용입니다.',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (60,'60번째 공지사항','60번째 공지사항 내용입니다.',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (61,'61번째 공지사항','61번째 공지사항 내용입니다.',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (62,'62번째 공지사항','62번째 공지사항 내용입니다.',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (63,'63번째 공지사항','63번째 공지사항 내용입니다.',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (64,'64번째 공지사항','64번째 공지사항 내용입니다.',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (65,'65번째 공지사항','65번째 공지사항 내용입니다.',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (66,'66번째 공지사항','66번째 공지사항 내용입니다.',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (67,'67번째 공지사항','67번째 공지사항 내용입니다.',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (68,'68번째 공지사항','68번째 공지사항 내용입니다.',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (69,'69번째 공지사항','69번째 공지사항 내용입니다.',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (70,'70번째 공지사항','70번째 공지사항 내용입니다.',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (71,'71번째 공지사항','71번째 공지사항 내용입니다.',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (72,'72번째 공지사항','72번째 공지사항 내용입니다.',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (73,'73번째 공지사항','73번째 공지사항 내용입니다.',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (74,'74번째 공지사항','74번째 공지사항 내용입니다.',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (75,'75번째 공지사항','75번째 공지사항 내용입니다.',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (76,'76번째 공지사항','76번째 공지사항 내용입니다.',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (77,'77번째 공지사항','77번째 공지사항 내용입니다.',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (78,'78번째 공지사항','78번째 공지사항 내용입니다.',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (79,'79번째 공지사항','79번째 공지사항 내용입니다.',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (80,'80번째 공지사항','80번째 공지사항 내용입니다.',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (81,'81번째 공지사항','81번째 공지사항 내용입니다.',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (82,'82번째 공지사항','82번째 공지사항 내용입니다.',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (83,'83번째 공지사항','83번째 공지사항 내용입니다.',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (84,'84번째 공지사항','84번째 공지사항 내용입니다.',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (85,'85번째 공지사항','85번째 공지사항 내용입니다.',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (86,'86번째 공지사항','86번째 공지사항 내용입니다.',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (87,'87번째 공지사항','87번째 공지사항 내용입니다.',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (88,'88번째 공지사항','88번째 공지사항 내용입니다.',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (89,'89번째 공지사항','89번째 공지사항 내용입니다.',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (90,'90번째 공지사항','90번째 공지사항 내용입니다.',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (91,'91번째 공지사항','91번째 공지사항 내용입니다.',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (92,'92번째 공지사항','92번째 공지사항 내용입니다.',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (93,'2022 하반기 궁온 2회차(달빛기행) 추첨 결과 안내','내용',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (94,'국가애도기간 중 행사 및 공연 안내(수문장 교대의식, 공연)','내용',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (95,'2023년 사회적 배려 대상자 초청 ‘창덕궁 달빛기행’ 최종 선정자 발표','내용',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (96,'(우천취소) 고궁음악회 4월 29일(토) 행사 취소 안내','내용',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (97,'(5.4.~5.6. 우천 취소) 고궁행사 행사 취소(고궁음악회, 달빛기행, 별빛야행, 창경궁 야연, 어린이 수문장)','내용',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (98,'‘창덕궁 달빛기행’ 5월 28일(일) 외국인 행사 우천취소 안내','내용',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (99,'6.6.(화), 6.7.(수) 수문장 교대의식 안내','내용',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (100,'밤의 석조전 예매 일자 변경 공지','내용',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (101,'○○○ 매장 - 덕수궁 지점 한복 대여 공지','내용',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (102,'‘경복궁 별빛야행’의 예매가 곧 시작됩니다.','내용',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
Insert into GAONNURIWEB.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_DATE,UPDATE_DATE,VIEW_COUNT) values (103,'제ㅔㅈ제ㅔ제제ㅔ 목고고고곡ㄱㄱ','as
da
sd
asd
as
daddd
d
d
d
d

???????????
잘
들어
가 
나
요??????????',to_date('23/08/09','RR/MM/DD'),to_date('23/08/09','RR/MM/DD'),0);
REM INSERTING into GAONNURIWEB.RENTAL_TBL
SET DEFINE OFF;
Insert into GAONNURIWEB.RENTAL_TBL (RENTAL_USER,RENTAL_PLACE,RENTAL_DATE,RENTAL_HANBOK,RENTAL_TOP_COLOR,RENTAL_TOP_SIZE,RENTAL_PANTS_COLOR,RENTAL_PANTS_SIZE,RENTAL_ACCESSORIES) values ('user01','경복궁',to_date('23/08/13','RR/MM/DD'),'[ 여성용 ] 여름 한복 세트','보라색','99','빨간색','77',null);
Insert into GAONNURIWEB.RENTAL_TBL (RENTAL_USER,RENTAL_PLACE,RENTAL_DATE,RENTAL_HANBOK,RENTAL_TOP_COLOR,RENTAL_TOP_SIZE,RENTAL_PANTS_COLOR,RENTAL_PANTS_SIZE,RENTAL_ACCESSORIES) values ('user01','창경궁',to_date('23/09/01','RR/MM/DD'),'[ 여성용 ] 여름 한복 세트','노란색','99','빨간색','55','부채');
Insert into GAONNURIWEB.RENTAL_TBL (RENTAL_USER,RENTAL_PLACE,RENTAL_DATE,RENTAL_HANBOK,RENTAL_TOP_COLOR,RENTAL_TOP_SIZE,RENTAL_PANTS_COLOR,RENTAL_PANTS_SIZE,RENTAL_ACCESSORIES) values ('user01','창경궁',to_date('23/08/25','RR/MM/DD'),'[ 여성용 ] 여름 한복 세트','분홍색','66','빨간색','66','자수 손가방');
REM INSERTING into GAONNURIWEB.RESERVE_TBL
SET DEFINE OFF;
Insert into GAONNURIWEB.RESERVE_TBL (RESERVE_USER,RESERVE_PLACE,RESERVE_DATE,RESERVE_TIME,RESERVE_PEOPLE,RESERVE_NAME,RESERVE_PHONE,RESERVE_EMAIL) values ('user01','창경궁',to_date('23/08/13','RR/MM/DD'),'18 : 40',2,'일용자','01011111111','user01@test.com');
Insert into GAONNURIWEB.RESERVE_TBL (RESERVE_USER,RESERVE_PLACE,RESERVE_DATE,RESERVE_TIME,RESERVE_PEOPLE,RESERVE_NAME,RESERVE_PHONE,RESERVE_EMAIL) values ('user01','창경궁',to_date('23/08/26','RR/MM/DD'),'18 : 40',3,'일용자','01011111111','user01@test.com');
Insert into GAONNURIWEB.RESERVE_TBL (RESERVE_USER,RESERVE_PLACE,RESERVE_DATE,RESERVE_TIME,RESERVE_PEOPLE,RESERVE_NAME,RESERVE_PHONE,RESERVE_EMAIL) values ('user02','종묘',to_date('23/08/05','RR/MM/DD'),'19 : 40',3,'이용자','01022222222',null);
Insert into GAONNURIWEB.RESERVE_TBL (RESERVE_USER,RESERVE_PLACE,RESERVE_DATE,RESERVE_TIME,RESERVE_PEOPLE,RESERVE_NAME,RESERVE_PHONE,RESERVE_EMAIL) values ('user02','덕수궁',to_date('23/09/15','RR/MM/DD'),'19 : 40',1,'이용자','01022222222',null);
Insert into GAONNURIWEB.RESERVE_TBL (RESERVE_USER,RESERVE_PLACE,RESERVE_DATE,RESERVE_TIME,RESERVE_PEOPLE,RESERVE_NAME,RESERVE_PHONE,RESERVE_EMAIL) values ('user01','경복궁',to_date('23/08/04','RR/MM/DD'),'18 : 40',10,'일용자','01011111111','user01@test.com');
Insert into GAONNURIWEB.RESERVE_TBL (RESERVE_USER,RESERVE_PLACE,RESERVE_DATE,RESERVE_TIME,RESERVE_PEOPLE,RESERVE_NAME,RESERVE_PHONE,RESERVE_EMAIL) values ('user01','창덕궁',to_date('23/09/01','RR/MM/DD'),'19 : 40',2,'일용자','01011111111','user01@test.com');
REM INSERTING into GAONNURIWEB.USER_TBL
SET DEFINE OFF;
Insert into GAONNURIWEB.USER_TBL (USER_ID,USER_PW,USER_NAME,USER_PHONE,USER_EMAIL,USER_EVENT_YN) values ('user01','pass01','일용자','01011111111','user01@test.com','Y');
Insert into GAONNURIWEB.USER_TBL (USER_ID,USER_PW,USER_NAME,USER_PHONE,USER_EMAIL,USER_EVENT_YN) values ('user02','pass02','이용자','01022222222',null,'N');
Insert into GAONNURIWEB.USER_TBL (USER_ID,USER_PW,USER_NAME,USER_PHONE,USER_EMAIL,USER_EVENT_YN) values ('admin','admin','관리자','01012345678',null,'N');
--------------------------------------------------------
--  DDL for Index SYS_C007233
--------------------------------------------------------

  CREATE UNIQUE INDEX "GAONNURIWEB"."SYS_C007233" ON "GAONNURIWEB"."NOTICE_TBL" ("NOTICE_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007208
--------------------------------------------------------

  CREATE UNIQUE INDEX "GAONNURIWEB"."SYS_C007208" ON "GAONNURIWEB"."USER_TBL" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007209
--------------------------------------------------------

  CREATE UNIQUE INDEX "GAONNURIWEB"."SYS_C007209" ON "GAONNURIWEB"."USER_TBL" ("USER_PHONE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table NOTICE_TBL
--------------------------------------------------------

  ALTER TABLE "GAONNURIWEB"."NOTICE_TBL" ADD PRIMARY KEY ("NOTICE_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GAONNURIWEB"."NOTICE_TBL" MODIFY ("NOTICE_SUBJECT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RENTAL_TBL
--------------------------------------------------------

  ALTER TABLE "GAONNURIWEB"."RENTAL_TBL" MODIFY ("RENTAL_PANTS_SIZE" NOT NULL ENABLE);
  ALTER TABLE "GAONNURIWEB"."RENTAL_TBL" MODIFY ("RENTAL_PANTS_COLOR" NOT NULL ENABLE);
  ALTER TABLE "GAONNURIWEB"."RENTAL_TBL" MODIFY ("RENTAL_TOP_SIZE" NOT NULL ENABLE);
  ALTER TABLE "GAONNURIWEB"."RENTAL_TBL" MODIFY ("RENTAL_TOP_COLOR" NOT NULL ENABLE);
  ALTER TABLE "GAONNURIWEB"."RENTAL_TBL" MODIFY ("RENTAL_HANBOK" NOT NULL ENABLE);
  ALTER TABLE "GAONNURIWEB"."RENTAL_TBL" MODIFY ("RENTAL_DATE" NOT NULL ENABLE);
  ALTER TABLE "GAONNURIWEB"."RENTAL_TBL" MODIFY ("RENTAL_PLACE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RESERVE_TBL
--------------------------------------------------------

  ALTER TABLE "GAONNURIWEB"."RESERVE_TBL" MODIFY ("RESERVE_PHONE" NOT NULL ENABLE);
  ALTER TABLE "GAONNURIWEB"."RESERVE_TBL" MODIFY ("RESERVE_NAME" NOT NULL ENABLE);
  ALTER TABLE "GAONNURIWEB"."RESERVE_TBL" MODIFY ("RESERVE_PEOPLE" NOT NULL ENABLE);
  ALTER TABLE "GAONNURIWEB"."RESERVE_TBL" MODIFY ("RESERVE_TIME" NOT NULL ENABLE);
  ALTER TABLE "GAONNURIWEB"."RESERVE_TBL" MODIFY ("RESERVE_DATE" NOT NULL ENABLE);
  ALTER TABLE "GAONNURIWEB"."RESERVE_TBL" MODIFY ("RESERVE_PLACE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USER_TBL
--------------------------------------------------------

  ALTER TABLE "GAONNURIWEB"."USER_TBL" ADD UNIQUE ("USER_PHONE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GAONNURIWEB"."USER_TBL" ADD PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GAONNURIWEB"."USER_TBL" MODIFY ("USER_PHONE" NOT NULL ENABLE);
  ALTER TABLE "GAONNURIWEB"."USER_TBL" MODIFY ("USER_NAME" NOT NULL ENABLE);
  ALTER TABLE "GAONNURIWEB"."USER_TBL" MODIFY ("USER_PW" NOT NULL ENABLE);
